name: browser
authors: ["Dart Team <misc@dartlang.org>"]
homepage: http://www.dartlang.org
description: >
 The bootstrap dart.js script for Dart apps running in the browser.

version: 0.7.5
environment:
  sdk: ">=0.7.5"
